# Generated by Django 6.0.2 on 2026-02-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
